'use strict';

module.exports = {
  RESPONSE_CODE: {
    SUCCESS: 200,
    SUCCESS_NEW_RESOURCE: 201,
    SUCCESS_WITHOUT_RESPONSE: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    NOT_FOUND: 404,
    FORBIDDEN: 403,
    INTERNAL_SERVER: 500,
    MAINTENANCE: 503,
    TOKEN_INAVLID: 498
  },

  USER_TYPE: {
    SUPER_ADMIN: 0,
    SUB_ADMIN: 1,
    USER: 2
  },
  ACCOUNT_STATUS: {
    INACTIVE: 0,
    ACTIVE: 1,
    DELETED: 2
  }
};
